---
# see the best practices in ansible docs for how to get started with creating roles etc.: 
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

- hosts: mattermost
  tasks:   
  - name: Update the apt-repositories and cache
    become: yes
    apt:
      update_cache: yes
      upgrade: yes
  
- hosts: mattermost
  vars:
    password: "{{ lookup('file', '/tmp/password.txt') }}"
  roles:
  - mysql_setup
  - mysql_cleanup 

- hosts: mattermost
  vars:
    password: "{{ lookup('file', '/tmp/password.txt') }}"
  tasks:
  - name: Create /root/.my.cnf with root password credentials
    become: yes
    copy:
      dest: "/root/.my.cnf"
      content: |
        [client]
        user=root
        password={{ password }}
  
- hosts: mattermost
  roles:
  - mattermost_setup
  - config_changes
  - mattermost_service_setup
  - mattermost_cli







    
