---
# Role that creates mattermost teams and users using cli

- name: Create mattermost user pest@getnada.com
  become: yes
  command: chdir=/opt/mattermost ./bin/mattermost user create --email pest@getnada.com --password Strong#Password123 --username pest
  
- name: Create mattermost user best@getnada.com
  become: yes
  command: chdir=/opt/mattermost ./bin/mattermost user create --email best@getnada.com --password Strong#Password123 --username best

- name: Create mattermost user test@getnada.com
  become: yes
  command: chdir=/opt/mattermost ./bin/mattermost user create --email test@getnada.com --password Strong#Password123 --username test

- name: Create mattermost team
  become: yes
  tags:
    - create
  command: chdir=/opt/mattermost ./bin/mattermost team create --name testteam --display_name "My New Team" --email test@getnada.com

- name: Add members to team
  become: yes
  tags:
    - create
  command: chdir=/opt/mattermost ./bin/mattermost team add newteam best@getnada.com pest@getnada.com test@getnada.com
